services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      PORT: 3000
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    command: npm test

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    environment:
      - VUE_APP_API_URL=http://localhost:3000

volumes:
  db-data:
